WITH A_T AS
(SELECT ID, PARENT_ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) YEAR
 FROM ECOLI_DATA 
WHERE ID is not null)

SELECT A.YEAR as YEAR, 
        (B.MAX_V-A.SIZE_OF_COLONY) as YEAR_DEV,
            A.ID
    FROM A_T A
    LEFT OUTER JOIN (
        SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_V
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    )as B
    ON B.YEAR = A.YEAR
    ORDER BY YEAR, YEAR_DEV;
    



/*
WITH MAX_SIZE AS
(SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
FROM ECOLI_DATA
GROUP BY 1)

SELECT M.YEAR, (MAX_SIZE - E.SIZE_OF_COLONY) YEAR_DEV, ID
FROM ECOLI_DATA E
LEFT JOIN MAX_SIZE M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 1, 2
*/